- name: Set variable
  set_fact:
    data_host:
      ip: "{{ ansible_facts.default_ipv4.address }}"
      port: "{{ port }}"
      password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length= length_password ) }}"

- name: UP wireguard vpn
  community.docker.docker_compose:
    project_name: vpn
    definition:
      version: '3.9'
      services:
        wireguard:
          image: weejewel/wg-easy
          container_name: wireguard_gui
          cap_add:
            - NET_ADMIN
            - SYS_MODULE
          environment:
            - WG_HOST={{ data_host.ip }}
            - PASSWORD={{ data_host.password }}
          volumes:
            - ~/.wg-easy:/etc/wireguard
          ports:
            - "{{ data_host.port }}:51821/tcp"
          sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
          restart: always
  register: output

- name: Show results
  debug:
    var: output

- name: Verify that the db and web services are running
  debug:
    msg: "
    WireGuard successfully launched.
    Url: 'http://{{ data_host.ip }}:{{ data_host.port }}'
    Password: {{ data_host.password }}
    "
  when: output.services.wireguard.wireguard_gui.state.running == true