- name: Install Docker
  hosts: servers
  become: true
  vars:
    port: 51821 # порт на якому працює gui інтерфейс
    length_password: 20 # довжина пароля
  roles:
    - docker_install
    - install_wireguard_in_docker
